### ISSUE TITLE
重复执行问题

### ISSUE THREAD

**Issue by bdingtech** [edge-sky/Bills-save#10]
https://github.com/edge-sky/Bills-save/blob/c406c43d541a5085d8b55f1951c550991336875b/mail.py#L317

如果一份账单邮件在三分钟内已经处理完毕，那么这封邮件似乎又会被当做新邮件重新执行

**Comment by edge-sky** [comment]
如果程序一直运行应该不会应该不会有这个问题，是不是完成一次同步后马上重启程序进行下次同步？


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月24日(周四) 下午2:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [edge-sky/Bills-save] 重复执行问题 (Issue #10)




 
https://github.com/edge-sky/Bills-save/blob/c406c43d541a5085d8b55f1951c550991336875b/mail.py#L317
 
如果一份账单邮件在三分钟内已经处理完毕，那么这封邮件似乎又会被当做新邮件重新执行
 
&mdash;

**Comment by bdingtech** [comment]
![CleanShot 2024-10-24 at 14 25 14@2x](https://github.com/user-attachments/assets/da913d48-5afa-471b-8c4f-b2a73b4119bd)
没有重启程序。当同步完成之后，会继续获取原来的账单密码，再走一遍流程。

**Comment by bdingtech** [comment]
delete_after_used: True
删掉邮件就正常了，就这样凑合着用吧😂
