### ISSUE TITLE
在获取支付宝邮件时异常

### ISSUE THREAD

**Issue by wangke8023** [edge-sky/Bills-save#5]
SMTP服务器连接成功
POP3服务器连接成功
尝试获取邮件
在获取支付宝邮件时异常: b'y5jb20vaHRtbC8yMDE5MTAyNC8yMDQ1Mi85OTY0MzMxNTcxODgxMjU4MS5qcGciIGhlaWdodD0iMzIiIGJvcmRlcj0iMCI+DQoJCQkJCQkJCQk8YSBocmVmPSJodHRwczovL2NmeXVtLnR5bnVuLmNvbS9qdW1wL2p1bXAucGhwP0FCOFBCaDBTUEJvQ1hrSmZVRlVTQWdBTlhrRlZXMEpTV2xVU0V4OWJVVVpXVzBCQUZCb1NDeXdURGs1V1JRWUxQQjBIRGhaYkZoNUFEaElQRDA1VFVVUlJWVVJSVUVKRFYwTVhFbDBGREI1QUVCWUlCd2NQRGhaYlVrWlJWVUpYVUVCUVZsVVRFUjliQWpzMFV4QXVMa1VxR2tvWEFpUlNGaW9MSlFNOEt5WVRPa0ZmRno5VVVnRUNJRW9NQVRSZkN4RVBXaDBDTkI4Tk9TZGZDUkZVTVI4Mk56SWVMaGtzREJjeFdnRThOekllS1I0b0RDb3hWZ1k4TkFSZk1COE9LQkl1TlFVSFVTWUxBRUFrRlJjaVVnSUZEaEFSTFRjdlVEOHlLZ1FyTnhRUkxEY3ZWejR5TWxaVkp3X18iIHRhcmdldD0iX2JsYW5rIj4NCgkJCQkJCQkJCTxpbWcgc3JjPSJodHRwczovL2NodWZhLmRvbnhpYW8uY29tL2h0bWwvMjAxOTEwMjQvMjA0NTIvMTI5NjkwMTU3MTg4MTI1ODIuanBnIiBoZWlnaHQ9IjMyIiBib3JkZXI9IjAiPg0KCQkJCQkJCQkJPC9hPg0KCQkJCQkJCQkJPGltZyBzcmM9Imh0dHBzOi8vY2h1ZmEuZG9ueGlhby5jb20vaHRtbC8yMDE5MTAyNC8yMDQ1Mi8xMDE0NDkxNTcxODgxMjU4My5qcGciIGhlaWdodD0iMzIiIGJvcmRlcj0iMCI+DQoJCQkJCQkJCQk8YSBocmVmPSJodHRwczovL2NmeXVtLnR5bnVuLmNvbS9qdW1wL2p1bXAucGhwP0FoQVNDaHdJWGtCQUZ3TUtYa0ZUVTB0VlJRY0hFQmhiVVVCZVVrZGZSUlFVREFZV1hrTkFEaElQRDA1VFVVUlJWVVJSVUVJbUVnSklBQndMUlFjV0R3Y1BGeDhEWGhzQUt6d09MQjBQQ3dVY0tSc3BCVHdQRnp0UkN3QXlOaHNRR1YwT0JoazFDeFVRVVJzUURVWXlWaWNOVVFNRUMwRXNPMFllRXlkUVZUa1FLUXM4T3g5VER3QUlLVUlKUEFfXyIgdGFyZ2V0PSJfYmxhbmsiPg0KCQkJCQkJCQkJPGltZyBzcmM9Imh0dHBzOi8vY2h1ZmEuZG9ueGlhby5jb20vaHRtbC8yMDE5MTAyNC8yMDQ1Mi80ODQ4OTgxNTcxODgxMjU4NC5qcGciIGhlaWdodD0iMzIiIGJvcmRlcj0iMCI+DQoJCQkJCQkJCQk8L2E+DQoJCQkJCQkJCQk8YSBocmVmPSJodHRwczovL2NmeXVtLnR5bnVuLmNvbS9qdW1wL2p1bXAucGhwP0FoQVNDaHdJWGtGQUZ3TUtYa0ZUVTB0VlJRY0hFQmhiVVVCZVVrZGZSUlFVREFZV1hrTkFEaElQRDA1VFVVUlJWVVJSVUVJbUVnSklBQndMUlFjV0R3Y1BGeDhEWGhzQUt6d09MQjBQQ3dVY0tSc3BCVHdQRnp0UkN3QXlOaHNRR1YwT0JoazFDeFVRVVJzUURVWXlWaWNOVVFNRUMwRXNPMFllRXlkUVZUa1FLUXM4T3g5VER3QUlLVUlKUEFfXyIgdGFyZ2V0PSJfYmxhbmsiPg0KCQkJCQkJCQkJPGltZyBzcmM9Imh0dHBzOi8vY2h1ZmEuZG9ueGlhby5jb20vaHRtbC8yMDE5MTAyNC8yMDQ1Mi81Nzk2ODAxNTcxODgxMjU4NS5qcGciIGhlaWdodD0iMzIiIGJvcmRlcj0iMCI+DQoJCQkJCQkJCQk8L2E+DQoJCQkJCQkJCQk8aW1nIHNyYz0iaHR0cHM6Ly9jaHVmYS5kb254aWFvLmNvbS9odG1sLzIwMTkxMDI0LzIwNDUyLzQ2Mzg0MzE1NzE4ODEyNTg2LmpwZyIgaGVpZ2h0PSIzMiIgYm9yZGVyPSIwIj4NCgkJCQkJCQkJPC90ZD4NCgkJCQkJCQk8L3RyPg0KCQkJCQkJCTwvdGJvZHk+DQoJCQkJCQk8L3RhYmxlPjxpbWcgc3JjPSJodHRwczovL2NmeXVtLnR5bnVuLmNvbS9qdW1wL29wZW4ucGhwP0Z3TUtYa0ZUVTB0VlJRY0hFQmhiVVVCZVVrZGZSUjRIQ2g5YlZrRlJWRVZSVkVCWEl3SVhUUkFKRGxVVkJoMENGeG9MQms1WFZrUlFVa0pWVUVWVCIgd2lkdGg9IjAiIGhlaWdodD0iMCIgc3R5bGU9ImRpc3BsYXk6bm9uZSIgLz4='
15秒后重试
[CRITICAL] <POPServer username:527767731@qq.com password:xxxxx pop.qq.com:995 ssl:True tls:False> duplicate login!
在获取支付宝邮件时异常: b'.'

**Comment by edge-sky** [comment]
看报错QQ&nbsp;邮检测到重复登录，请尝试不要频繁启停程序或切换其他邮箱重试


---Original---
From: ***@***.***&gt;
Sent at: 2024年10月16日(Wed) Noon1:47
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [edge-sky/Bills-save] 在获取支付宝邮件时异常 (Issue #5)




 
SMTP服务器连接成功
 POP3服务器连接成功
 尝试获取邮件
 在获取支付宝邮件时异常: b'y5jb20vaHRtbC8yMDE5MTAyNC8yMDQ1Mi85OTY0MzMxNTcxODgxMjU4MS5qcGciIGhlaWdodD0iMzIiIGJvcmRlcj0iMCI+DQoJCQkJCQkJCQk8YSBocmVmPSJodHRwczovL2NmeXVtLnR5bnVuLmNvbS9qdW1wL2p1bXAucGhwP0FCOFBCaDBTUEJvQ1hrSmZVRlVTQWdBTlhrRlZXMEpTV2xVU0V4OWJVVVpXVzBCQUZCb1NDeXdURGs1V1JRWUxQQjBIRGhaYkZoNUFEaElQRDA1VFVVUlJWVVJSVUVKRFYwTVhFbDBGREI1QUVCWUlCd2NQRGhaYlVrWlJWVUpYVUVCUVZsVVRFUjliQWpzMFV4QXVMa1VxR2tvWEFpUlNGaW9MSlFNOEt5WVRPa0ZmRno5VVVnRUNJRW9NQVRSZkN4RVBXaDBDTkI4Tk9TZGZDUkZVTVI4Mk56SWVMaGtzREJjeFdnRThOekllS1I0b0RDb3hWZ1k4TkFSZk1COE9LQkl1TlFVSFVTWUxBRUFrRlJjaVVnSUZEaEFSTFRjdlVEOHlLZ1FyTnhRUkxEY3ZWejR5TWxaVkp3X18iIHRhcmdldD0iX2JsYW5rIj4NCgkJCQkJCQkJCTxpbWcgc3JjPSJodHRwczovL2NodWZhLmRvbnhpYW8uY29tL2h0bWwvMjAxOTEwMjQvMjA0NTIvMTI5NjkwMTU3MTg4MTI1ODIuanBnIiBoZWlnaHQ9IjMyIiBib3JkZXI9IjAiPg0KCQkJCQkJCQkJPC9hPg0KCQkJCQkJCQkJPGltZyBzcmM9Imh0dHBzOi8vY2h1ZmEuZG9ueGlhby5jb20vaHRtbC8yMDE5MTAyNC8yMDQ1Mi8xMDE0NDkxNTcxODgxMjU4My5qcGciIGhlaWdodD0iMzIiIGJvcmRlcj0iMCI+DQoJCQkJCQkJCQk8YSBocmVmPSJodHRwczovL2NmeXVtLnR5bnVuLmNvbS9qdW1wL2p1bXAucGhwP0FoQVNDaHdJWGtCQUZ3TUtYa0ZUVTB0VlJRY0hFQmhiVVVCZVVrZGZSUlFVREFZV1hrTkFEaElQRDA1VFVVUlJWVVJSVUVJbUVnSklBQndMUlFjV0R3Y1BGeDhEWGhzQUt6d09MQjBQQ3dVY0tSc3BCVHdQRnp0UkN3QXlOaHNRR1YwT0JoazFDeFVRVVJzUURVWXlWaWNOVVFNRUMwRXNPMFllRXlkUVZUa1FLUXM4T3g5VER3QUlLVUlKUEFfXyIgdGFyZ2V0PSJfYmxhbmsiPg0KCQkJCQkJCQkJPGltZyBzcmM9Imh0dHBzOi8vY2h1ZmEuZG9ueGlhby5jb20vaHRtbC8yMDE5MTAyNC8yMDQ1Mi80ODQ4OTgxNTcxODgxMjU4NC5qcGciIGhlaWdodD0iMzIiIGJvcmRlcj0iMCI+DQoJCQkJCQkJCQk8L2E+DQoJCQkJCQkJCQk8YSBocmVmPSJodHRwczovL2NmeXVtLnR5bnVuLmNvbS9qdW1wL2p1bXAucGhwP0FoQVNDaHdJWGtGQUZ3TUtYa0ZUVTB0VlJRY0hFQmhiVVVCZVVrZGZSUlFVREFZV1hrTkFEaElQRDA1VFVVUlJWVVJSVUVJbUVnSklBQndMUlFjV0R3Y1BGeDhEWGhzQUt6d09MQjBQQ3dVY0tSc3BCVHdQRnp0UkN3QXlOaHNRR1YwT0JoazFDeFVRVVJzUURVWXlWaWNOVVFNRUMwRXNPMFllRXlkUVZUa1FLUXM4T3g5VER3QUlLVUlKUEFfXyIgdGFyZ2V0PSJfYmxhbmsiPg0KCQkJCQkJCQkJPGltZyBzcmM9Imh0dHBzOi8vY2h1ZmEuZG9ueGlhby5jb20vaHRtbC8yMDE5MTAyNC8yMDQ1Mi81Nzk2ODAxNTcxODgxMjU4NS5qcGciIGhlaWdodD0iMzIiIGJvcmRlcj0iMCI+DQoJCQkJCQkJCQk8L2E+DQoJCQkJCQkJCQk8aW1nIHNyYz0iaHR0cHM6Ly9jaHVmYS5kb254aWFvLmNvbS9odG1sLzIwMTkxMDI0LzIwNDUyLzQ2Mzg0MzE1NzE4ODEyNTg2LmpwZyIgaGVpZ2h0PSIzMiIgYm9yZGVyPSIwIj4NCgkJCQkJCQkJPC90ZD4NCgkJCQkJCQk8L3RyPg0KCQkJCQkJCTwvdGJvZHk+DQoJCQkJCQk8L3RhYmxlPjxpbWcgc3JjPSJodHRwczovL2NmeXVtLnR5bnVuLmNvbS9qdW1wL29wZW4ucGhwP0Z3TUtYa0ZUVTB0VlJRY0hFQmhiVVVCZVVrZGZSUjRIQ2g5YlZrRlJWRVZSVkVCWEl3SVhUUkFKRGxVVkJoMENGeG9MQms1WFZrUlFVa0pWVUVWVCIgd2lkdGg9IjAiIGhlaWdodD0iMCIgc3R5bGU9ImRpc3BsYXk6bm9uZSIgLz4='
 15秒后重试
 [CRITICAL] <POPServer ***@***.*** password:xxxxx pop.qq.com:995 ssl:True tls:False&gt; duplicate login!
 在获取支付宝邮件时异常: b'.'
 
&mdash;

**Comment by wangke8023** [comment]
换了邮箱之后报这个错误：
在获取支付宝邮件时异常: 'NoneType' object has no attribute 'groups'

**Comment by edge-sky** [comment]
检查支付宝发送账单信息中&nbsp;显示对手信息&nbsp;是否勾选


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月16日(周三) 下午3:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [edge-sky/Bills-save] 在获取支付宝邮件时异常 (Issue #5)




 
换了邮箱之后报这个错误：
 在获取支付宝邮件时异常: 'NoneType' object has no attribute 'groups'
 
&mdash;

**Comment by wangke8023** [comment]
> 检查支付宝发送账单信息中&nbsp;显示对手信息&nbsp;是否勾选
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年10月16日(周三) 下午3:11 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [edge-sky/Bills-save] 在获取支付宝邮件时异常 (Issue #5) 换了邮箱之后报这个错误： 在获取支付宝邮件时异常: 'NoneType' object has no attribute 'groups' &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

确认勾选了，而且这个是默认就勾选

**Comment by wangke8023** [comment]
莫名其妙就好了，但是出现了新的问题 ，我已经邮件回复了解压密码，但是日志一直提示获取不到解压密码
![image](https://github.com/user-attachments/assets/473a68e4-c84c-4d7a-a405-5c9c3547d99f)

**Comment by wangke8023** [comment]
加了日志打印，发现是会进入到黑名单跳过逻辑，把黑名单手动置空，就可以了
