### ISSUE TITLE
Could not find database with ID

### ISSUE THREAD

**Issue by wangke8023** [edge-sky/Bills-save#6]
![image](https://github.com/user-attachments/assets/d189a387-4c7a-4534-ae27-c619113858b9)
![image](https://github.com/user-attachments/assets/d7a9679e-8143-4165-bcb1-6519cba4cb19)
明明已经链接好了集成，但是提示：
'Could not find database with ID: 1212250f-3985-801c-a770-cce8ffaca1bd. Make sure the relevant pages and databases are shared with your integration.

**Comment by edge-sky** [comment]
请确认你的数据库页面&nbsp;id&nbsp;填写正确，获取方法详见&nbsp;readme&nbsp;或&nbsp;config.yaml


---Original---
From: ***@***.***&gt;
Date: Thu, Oct 17, 2024 09:49 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [edge-sky/Bills-save] Could not find database with ID (Issue #6)




 
image.png (view on web)
 image.png (view on web)
 明明已经链接好了集成，但是提示：
 'Could not find database with ID: 1212250f-3985-801c-a770-cce8ffaca1bd. Make sure the relevant pages and databases are shared with your integration.
 
&mdash;

**Comment by Corey01327** [comment]
跟楼主遇到了同样的问题，已经完成集成操作，但是还是提示Could not find database with ID: 1a2a69a7-c909-80a1-bd72-f478d00a1d10. Make sure the relevant pages and databases are shared with your integration.
没有发现如何 Debug（信息按照 readme格式要求往 config.yaml里填的）
